name: Static Code Analysis

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Execute Code Static Analysis (PSALM)
      run: |
        composer require --dev vimeo/psalm
        ./vendor/bin/psalm --init
        composer require --dev psalm/plugin-laravel
        ./vendor/bin/psalm-plugin enable psalm/plugin-laravel
        vendor/bin/psalm
